pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Place your build commands here
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Place your test commands here
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                // Place your package commands here
                sh 'mvn package'
            }
        }

        stage('Deliver') {
            steps {
                // Run the delivery script
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
